### ISSUE TITLE
Mis-spelled or intentional: MemeoryTestAPI ?

### ISSUE THREAD

**Issue by kleopatra** [Sandec/JMemoryBuddy#2]
or some joke that I don't understand? Similarly, the method memoryTest has local field names that look a bit scrambled - toBeColelcted and toBeNotColelcted. But then those might also be a kind of joke :)

Incidentally, I have been thinking about such testing just yesterday (with no valid outcome), so will try your class later today, thanks for sharing :)

Jeanette

**Comment by FlorianKirmaier** [comment]
Luckily only the internal variables are affected. : )
Thank you for the feedback.
I will fix them with the next version.

**Comment by kleopatra** [comment]
well, except for the interface - or isn't that meant to be public?

**Comment by FlorianKirmaier** [comment]
I've fixed the letter scrambling.
Do you see any other misspelling?
collectible seems to be wrong because it has a different meaning: https://www.grammar-monster.com/easily_confused/collectable_collectible.htm
But maybe I'm wrong, I'm not a native speaker.

**Comment by kleopatra** [comment]
me neither :) What I meant is the interface that I mentioned in the title of this:

public static interface MemeoryTestAPI

shouldn't that be MemoryTestAPI? Or not intended to be public? Or what am I missing?

**Comment by FlorianKirmaier** [comment]
Now it's fixed!
It's intended to be public, but because nowadays sane people use lambdas, no one would ever have to write the misspelled class name.

I think the idea of writing these kinds of tests is often "invented". 
But for many reasons, these solutions often are not stable and are not moved into a library.
