### ISSUE TITLE
Add Automatic-Module-Name to Manifest

### ISSUE THREAD

**Issue by abhinayagarwal** [Sandec/JMemoryBuddy#4]
ControlsFX cannot use this library for JDK 9 and above, as there is no entry for `Automatic-Module-Name` in its JAR Manifest.

It was introduced in ControlsFX as a part of this [PR](https://github.com/controlsfx/controlsfx/pull/1202)

**Comment by FlorianKirmaier** [comment]
@abhinayagarwal 
I've added `Automatic-Module-Name` to the new release 0.2.0. :-)
